# See https://ezcv.readthedocs.io for documentation
name: Victor Dong
theme: ethereal
resume: false
avatar: https://minervastrategies.com/wp-content/uploads/2016/03/default-avatar.jpg # A path to an image of yourself (can also be a URL)
biography: A description of yourself # This field is for writing about yourself you can add a > to span multiple lines